// ================================================================
// Curated Seed Data — Real directories, subreddits, newsletters,
// and verified Facebook groups
// ================================================================

export const SEED_DATA = {
  subreddits: [
    // ── General startup / indie (safe to post in with story-first approach) ──
    { name: 'r/SideProject', members: '180K', url: 'https://reddit.com/r/SideProject', postingRules: 'Share your project, what you built and why. Story format works best. No hard sells.', tags: ['startup', 'indie', 'project', 'launch'] },
    { name: 'r/alphaandbetausers', members: '45K', url: 'https://reddit.com/r/alphaandbetausers', postingRules: 'Explicitly invite users to try your beta. URLs and product links are encouraged here.', tags: ['launch', 'beta', 'testing', 'feedback', 'startup', 'indie'] },
    { name: 'r/Entrepreneur', members: '3.5M', url: 'https://reddit.com/r/Entrepreneur', postingRules: 'Focus on the entrepreneurial journey, lessons learned, not the product itself.', tags: ['business', 'startup', 'entrepreneur'] },
    { name: 'r/indiehackers', members: '35K', url: 'https://reddit.com/r/indiehackers', postingRules: 'Milestone posts, revenue updates, and lessons learned. Be transparent with numbers.', tags: ['indie', 'saas', 'developer', 'build'] },
    { name: 'r/SaaS', members: '75K', url: 'https://reddit.com/r/SaaS', postingRules: 'Technical and business insights about running SaaS. Mention your tool naturally if relevant.', tags: ['saas', 'startup', 'software'] },
    { name: 'r/startups', members: '1.2M', url: 'https://reddit.com/r/startups', postingRules: 'Share insights, ask questions, discuss your journey. No direct self-promotion posts.', tags: ['startup', 'business', 'saas', 'launch'] },
    { name: 'r/smallbusiness', members: '2M', url: 'https://reddit.com/r/smallbusiness', postingRules: 'Practical advice and questions for small business owners. Mention your tool in comments naturally.', tags: ['business', 'small business', 'entrepreneur'] },
    { name: 'r/freelance', members: '350K', url: 'https://reddit.com/r/freelance', postingRules: 'Freelancing tips and discussions. Share tools that genuinely helped you.', tags: ['freelance', 'freelancer', 'service'] },
    { name: 'r/digital_marketing', members: '250K', url: 'https://reddit.com/r/digital_marketing', postingRules: 'Marketing insights and case studies. Data and results posts perform best.', tags: ['marketing', 'growth', 'distribution'] },
    { name: 'r/nocode', members: '90K', url: 'https://reddit.com/r/nocode', postingRules: 'No-code tool showcases are welcome. Show what you built, link is fine.', tags: ['nocode', 'tool', 'builder', 'tech'] },
    { name: 'r/InternetIsBeautiful', members: '17M', url: 'https://reddit.com/r/InternetIsBeautiful', postingRules: 'Share as "I made this" or "Found this". Must be a genuinely useful or delightful free tool. No paywalled products.', tags: ['launch', 'product', 'web', 'tool'] },
    { name: 'r/webdev', members: '2.5M', url: 'https://reddit.com/r/webdev', postingRules: 'Technical showcases welcome. Show your code, your approach, your stack.', tags: ['developer', 'web', 'tech', 'programming'] },
    { name: 'r/artificial', members: '500K', url: 'https://reddit.com/r/artificial', postingRules: 'AI tools and research. Share what your AI does and how it works technically.', tags: ['ai', 'ml', 'artificial intelligence'] },
    { name: 'r/MachineLearning', members: '3M', url: 'https://reddit.com/r/MachineLearning', postingRules: 'Research and technical ML content. Share papers, methods, or technical insights.', tags: ['ai', 'ml', 'deep learning'] },
    { name: 'r/reactjs', members: '400K', url: 'https://reddit.com/r/reactjs', postingRules: 'React projects and technical discussion. Showcase posts with source code or demo are fine.', tags: ['react', 'frontend', 'javascript', 'developer'] },
    { name: 'r/nextjs', members: '150K', url: 'https://reddit.com/r/nextjs', postingRules: 'Next.js projects and technical Q&A. Show your implementation, ask for feedback.', tags: ['nextjs', 'react', 'fullstack', 'developer'] },
    { name: 'r/design_critiques', members: '90K', url: 'https://reddit.com/r/design_critiques', postingRules: 'Post screenshots of your UI and ask for honest feedback. Very supportive community.', tags: ['design', 'ui', 'ux', 'feedback'] },
    { name: 'r/programming', members: '6M', url: 'https://reddit.com/r/programming', postingRules: 'Technical articles and showcases. No promotional posts — must be educational or technical.', tags: ['developer', 'programming', 'tech'] },
    { name: 'r/growthacking', members: '120K', url: 'https://reddit.com/r/growthacking', postingRules: 'Growth tactics and case studies. Share your actual results and the method behind them.', tags: ['growth', 'marketing', 'startup'] },
    { name: 'r/productivity', members: '2.5M', url: 'https://reddit.com/r/productivity', postingRules: 'Only mention your tool if it genuinely solves a productivity problem being discussed.', tags: ['productivity', 'tool', 'saas'] },
  ],

  // ── Verified Facebook Groups (manually curated, large & active) ──
  facebookGroups: [
    { name: 'Indie Hackers & Entrepreneurs', members: '180K', url: 'https://www.facebook.com/groups/indiehackers', tags: ['startup', 'indie', 'entrepreneur', 'saas'] },
    { name: 'SaaS Growth Hacks', members: '85K', url: 'https://www.facebook.com/groups/saasgrowth', tags: ['saas', 'growth', 'startup', 'marketing'] },
    { name: 'Entrepreneurs & Startups', members: '430K', url: 'https://www.facebook.com/groups/entrepreneursstartups', tags: ['startup', 'entrepreneur', 'business'] },
    { name: 'Side Hustle Nation Community', members: '220K', url: 'https://www.facebook.com/groups/sidehustlenation', tags: ['startup', 'indie', 'side hustle', 'entrepreneur'] },
    { name: 'Digital Marketing Questions & Answers', members: '330K', url: 'https://www.facebook.com/groups/digitalmarketingquestions', tags: ['marketing', 'growth', 'digital'] },
    { name: 'Web Designers & Developers - Help & Share', members: '240K', url: 'https://www.facebook.com/groups/webdesignersdevelopers', tags: ['developer', 'web', 'design', 'tech'] },
    { name: 'Freelancers Hub (Work From Anywhere)', members: '390K', url: 'https://www.facebook.com/groups/freelancershub', tags: ['freelance', 'freelancer', 'service', 'remote'] },
    { name: 'No Code Founders', members: '95K', url: 'https://www.facebook.com/groups/nocodefounders', tags: ['nocode', 'tool', 'startup', 'founder'] },
    { name: 'Online Business Owners Collective', members: '160K', url: 'https://www.facebook.com/groups/onlinebusinessowners', tags: ['business', 'startup', 'entrepreneur', 'saas'] },
    { name: 'AI Tools & Prompts for Business', members: '145K', url: 'https://www.facebook.com/groups/aitoolsbusiness', tags: ['ai', 'tool', 'business', 'startup'] },
    { name: 'React Developers Community', members: '110K', url: 'https://www.facebook.com/groups/reactdevelopers', tags: ['react', 'developer', 'frontend', 'javascript'] },
    { name: 'Female Founders & Women in Business', members: '200K', url: 'https://www.facebook.com/groups/femalefounders', tags: ['startup', 'founder', 'entrepreneur', 'business'] },
    { name: 'Small Business Owners Support Group', members: '480K', url: 'https://www.facebook.com/groups/smallbizowners', tags: ['small business', 'entrepreneur', 'business'] },
    { name: 'Growth Hacking Strategies', members: '75K', url: 'https://www.facebook.com/groups/growthhackingstrategies', tags: ['growth', 'marketing', 'startup', 'saas'] },
    { name: 'Startup Funding & Investment Network', members: '130K', url: 'https://www.facebook.com/groups/startupfunding', tags: ['startup', 'funding', 'investor', 'business'] },
  ],

  directories: [
    { name: 'Product Hunt', url: 'https://www.producthunt.com/posts/new', tags: ['product', 'launch', 'startup', 'general'] },
    { name: 'Indie Hackers Products', url: 'https://www.indiehackers.com/products', tags: ['indie', 'startup', 'saas', 'general'] },
    { name: 'BetaList', url: 'https://betalist.com/submit', tags: ['beta', 'startup', 'launch', 'general'] },
    { name: 'Launching Next', url: 'https://www.launchingnext.com/submit/', tags: ['startup', 'launch', 'general'] },
    { name: 'SaaSHub', url: 'https://www.saashub.com/submit', tags: ['saas', 'software', 'general'] },
    { name: 'AlternativeTo', url: 'https://alternativeto.net/add-app/', tags: ['alternative', 'software', 'general'] },
    { name: "There's An AI For That", url: 'https://theresanaiforthat.com/submit/', tags: ['ai', 'tool', 'general'] },
    { name: 'ToolPilot', url: 'https://www.toolpilot.ai/submit', tags: ['ai', 'tool', 'general'] },
    { name: 'Uneed', url: 'https://www.uneed.best/submit-a-tool', tags: ['tool', 'startup', 'general'] },
    { name: 'MicroLaunch', url: 'https://microlaunch.net/submit', tags: ['indie', 'startup', 'launch', 'general'] },
    { name: 'Hacker News (Show HN)', url: 'https://news.ycombinator.com/submit', tags: ['tech', 'startup', 'developer', 'general'] },
    { name: 'GetApp', url: 'https://www.getapp.com/', tags: ['saas', 'software', 'b2b', 'general'] },
    { name: 'G2', url: 'https://sell.g2.com/product-listing-request', tags: ['saas', 'software', 'b2b', 'general'] },
    { name: 'Capterra', url: 'https://www.capterra.com/vendors/sign-up', tags: ['saas', 'software', 'b2b', 'general'] },
    { name: 'StackShare', url: 'https://stackshare.io/add', tags: ['developer', 'tool', 'tech', 'general'] },
    { name: 'DevHunt', url: 'https://devhunt.org/add-tool', tags: ['developer', 'tool', 'tech', 'general'] },
    { name: 'Toolify.ai', url: 'https://www.toolify.ai/submit', tags: ['ai', 'tool', 'general'] },
    { name: 'FuturePedia', url: 'https://www.futurepedia.io/submit-tool', tags: ['ai', 'tool', 'general'] },
  ],

  newsletters: [
    { name: 'TLDR', subscribers: '1.2M', url: 'https://tldr.tech/newsletter/advertise', description: 'Daily tech digest for developers and startup founders', tags: ['tech', 'developer', 'startup', 'general'] },
    { name: 'Hacker Newsletter', subscribers: '60K', url: 'https://hackernewsletter.com/', description: 'Weekly best of Hacker News', tags: ['tech', 'startup', 'developer'] },
    { name: 'Indie Hackers Newsletter', subscribers: '100K', url: 'https://www.indiehackers.com/', description: 'Indie maker stories, revenues, and tactics', tags: ['indie', 'startup', 'saas'] },
    { name: "Ben's Bites", subscribers: '500K', url: 'https://bensbites.beehiiv.com/', description: 'Daily AI tools and news roundup', tags: ['ai', 'tech', 'startup'] },
    { name: 'Product Hunt Daily', subscribers: '500K', url: 'https://www.producthunt.com/', description: 'Top products of the day sent to subscribers', tags: ['product', 'startup', 'launch'] },
    { name: 'Starter Story', subscribers: '80K', url: 'https://www.starterstory.com/newsletter', description: 'How founders built their businesses — interview style', tags: ['startup', 'business', 'entrepreneur'] },
    { name: 'Console.dev', subscribers: '30K', url: 'https://console.dev/', description: 'Interesting developer tools reviewed weekly', tags: ['developer', 'tool', 'tech'] },
    { name: 'Bytes.dev', subscribers: '200K', url: 'https://bytes.dev/', description: 'JavaScript and frontend ecosystem news', tags: ['javascript', 'developer', 'frontend'] },
    { name: 'Dense Discovery', subscribers: '35K', url: 'https://www.densediscovery.com/', description: 'Design, tech and culture for thoughtful people', tags: ['design', 'tech', 'productivity'] },
    { name: 'Changelog Weekly', subscribers: '25K', url: 'https://changelog.com/news', description: 'Open source news and developer tools', tags: ['developer', 'open source', 'tech'] },
  ],
};
